### ISSUE TITLE
Android - Build error when used with TNSGauge (Telerik RadGauge)

### ISSUE THREAD

**Issue by ipald** [nativescript-community/ui-material-components#258] opened 2021-04-01 12:42 UTC
### Make sure to check the demo app(s) for sample usage 
Yes
### Make sure to check the existing issues in this repository 
Yes

### Which platform(s) does your issue occur on?
- Android only
- Android latest version
- Emulator and device, failed compiling

### Please, provide the following version numbers that your issue occurs with:
- CLI: 7.2.1
- Cross-platform modules: 7.1.4
- Plugin(s): nativescript-ui-gauge@7.0.2

### Please, tell us how to recreate the issue in as much detail as possible. 
If ui-material-bottomsheet is used with Telerik's RadGauge (https://github.com/NativeScript/docs/blob/master/docs//ui/components/Gauge/getting-started.md) the android build fails with error
```
Execution failed for task ':app:mergeDebugResources'.
Android resource compilation failed
/home/user/.gradle/caches/transforms-2/files-2.1/fd00fa2ccaf7ee2de0534d6843463094/jetified-TNSGauge-release/res/values/values.xml:29:5-40:25: AAPT: error: duplicate value for resource 'attr/circleRadius' with config ''.
    
/home/user/.gradle/caches/transforms-2/files-2.1/fd00fa2ccaf7ee2de0534d6843463094/jetified-TNSGauge-release/res/values/values.xml:29:5-40:25: AAPT: error: resource previously defined here.
    
/home/user/myproject/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml: AAPT: error: file failed to compile.
```
I've double checked with two different project: in the first one I've stripped out ui-material-bottomsheet

Edit: seems that other plugins (not used by me) have the same issue [https://github.com/triniwiz/nativescript-plugins/issues/27](https://github.com/triniwiz/nativescript-plugins/issues/27)

**Comment by farfromrefug** [comment] 2021-04-12 12:13
@ipald i ll close this the issue is with ui-gauge

**Closed by farfromrefug** 2021-04-12 12:13 UTC

**Comment by cjohn001** [comment] 2021-04-13 23:00
Hello, I am observing the same issue. Has anyone found a workaround?

**Comment by farfromrefug** [comment] 2021-04-14 05:15
@cjohn001 no easy workaround ui gauge us doing something it should not do .

**Comment by cjohn001** [comment] 2021-04-14 16:18
@farfromrefug: Thanks for letting be know. I hope then we see an update from ui gauge soon. As the issue will likely withhold quite a couple of people from migrating to NS8.

**Comment by farfromrefug** [comment] 2021-04-14 17:36
@cjohn001 dont expect it. you should migrate to another solution

**Comment by cjohn001** [comment] 2021-07-09 00:07
@farfromrefug: I have access to the ui gauge sources. Unfortunately, I have no idea how to fix the issue without renaming the attr/circleRadius and breaking the API.
I could not find were attr/circleRadius is used in the ui-material-components plugin. Can you give me directions what would need to be done to resolve the issue without renaming the circleRadius attribute on ui gauge?

**Comment by farfromrefug** [comment] 2021-07-09 06:11
@cjohn001 your are absolutely right the only way is to rename the attribute. but it won't change much for N users as N mostly never uses XML layout attributes (only used when using android layout files)
