### ISSUE TITLE
MDTextField this.nativeView.getLineSpacingExtra is not a function

### ISSUE THREAD

**Issue by abbieben07** [nativescript-community/ui-material-components#319] opened 2021-07-26 12:26 UTC
Please i have been struggling to make use of your material textfield in my project. i will really appreciate your assistance

### Which platform(s) does your issue occur on?
- Android 
- Android API 29
- Both Emulator and Device
- Samsung A72

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.2
- Cross-platform modules: 8.0.8
- Runtime(s): 8.0.0
- Plugin(s): 5.3.11

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
Setup Nativescript using Vue, then add Material Textfield to the page and it will display this error;

### This is Error Trace
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: TypeError: this.nativeView.getLineSpacingExtra is not a function
System.err:
System.err: StackTrace:
System.err: [lineHeight:getDefault](file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\text-base\index.android.js:278:0)
System.err:     at applyAllNativeSetters(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\properties\index.js:1150:0)
System.err:     at initNativeView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\properties\index.js:1080:0)
System.err:     at onResumeNativeUpdates(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:737:22)      
System.err:     at _resumeNativeUpdates(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:280:0)        
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:235:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)       
System.err:     at callLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)       
System.err:     at callLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)       
System.err:     at callLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)
System.err:     at callLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)       
System.err:     at callLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\layouts\layout-base-common.js:101:0)
System.err:     at eachChild(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)       
System.err:     at callLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:237:0)
System.err:     at eachChildView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\content-view\index.js:65:0)
System.err:     at eachChildView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\page\page-common.js:106:0)
System.err:     at eachChild(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\view-common.js:759:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:236:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view\index.android.js:291:0)
System.err:     at onLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\page\index.android.js:38:0)
System.err:     at (file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at callFunctionWithSuper(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:312:0)       
System.err:     at callLoaded(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:318:0)
System.err:     at loadView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:458:0)
System.err:     at _addViewCore(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:453:0)
System.err:     at _addView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\core\view-base\index.js:439:0)
System.err:     at onCreateView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\frame\index.android.js:739:0)
System.err:     at onCreateView(file: app\webpack:\@nativescript\template-blank-vue\node_modules\@nativescript\core\ui\frame\fragment.android.js:25:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
System.err:     at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
System.err:     at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
System.err:     at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
System.err:     at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
System.err:     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
System.err:     at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
System.err:     at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
System.err:     at android.os.Handler.handleCallback(Handler.java:938)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:246)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:8506)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by dangrima90** [comment] 2022-09-26 16:18
@farfromrefug I'm using NS7 and up until a few days ago I've never faced any issues. However this week I'm getting this error `this.nativeView.getLineSpacingExtra is not a function`.

From the mentioned issue it seems that the fix was done for NS8. Is there any way that this could be fixed for NS7?

**Comment by dangrima90** [comment] 2022-09-27 06:23
I've managed to replicate the issue without my wrapper component. The issue occurs when line height is set:

This works fine:

```html
<MDTextField
  :style="{ fontSize: '30px' }"
  placeholderColor="gray"
  hint="This is a test"
  text="ABC"
  @loaded="onInputLoad"
/>
```

This fails:

```html
<MDTextField
  :style="{ fontSize: '30px', lineHeight: '1.5' }"
  placeholderColor="gray"
  hint="This is a test"
  text="ABC"
  @loaded="onInputLoad"
/>
```

In the application I'm working on Tailwind CSS is being used, therefore to set the font size a utility class which in my case also sets the line height.

```html
<MDTextField
  class="text-xl"
  placeholderColor="gray"
  hint="This is a test"
  text="ABC"
  @loaded="onInputLoad"
/>
```

```css
.text-xl {
  font-size: 1.25rem/* 20px */;
  line-height: 1.5;
}
```

Is it not possible to set a line height with the text field? I'm a bit confused as with version `v7.0.25` this used to work, however now even reverting to `v7.0.25` it is failing.

**Comment by farfromrefug** [comment] 2022-09-27 07:13
@dangrima90  @abbieben07 i ll take a look.

**Comment by farfromrefug** [comment] 2022-09-27 09:05
@dangrima90 @abbieben07 what s your N version ? It seems you are using an old version of N as the code the issue is refering to ` this.nativeView.getLineSpacingExtra`. does not exist (anymore). It has been quite some time since it changed (https://github.com/NativeScript/NativeScript/commit/0d0d0382ad238e0df1332506741142e02e01e34c)
And the material components need that commit. Either upgrade N or use older version of the plugin (look in releases for a version released before the date of the linked commit).

**Comment by dangrima90** [comment] 2022-09-27 10:48
@farfromrefug yes at the moment we're in the process of upgrading to NS 8, in the meantime we still need to maintain our production version with is NS 7.

For now I will probably implement a workaround to not have line height set in this case.

**Comment by farfromrefug** [comment] 2022-09-27 10:58
@dangrima90 ok i ll close this issue as it is a dep issue

**Closed by farfromrefug** 2022-09-27 10:58 UTC
