### ISSUE TITLE
MDTabContentItem not rendering after changing android theme

### ISSUE THREAD

**Issue by mukaschultze** [nativescript-community/ui-material-components#326] opened 2021-08-19 01:01 UTC
### Which platform(s) does your issue occur on?
- Android 11
- emulator or device? Both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 8.0.2-next-08-13-2021-1128363962
- Runtime(s): 8.0.0
- Plugin(s): `@nativescript-community/ui-material-bottom-navigation": "^5.3.11` 

### Please, tell us how to recreate the issue in as much detail as possible. 
Changing the OS theme while the app is running causes the `MDTabContentItem` to stop rendering until the current tab is changed.

The issue possibly lies in this piece of code since the `fragment` is found by name/tag, so it is not null, but it's not a valid fragment:

https://github.com/nativescript-community/ui-material-components/blob/master/src/bottom-navigation/index.android.ts#L525-L545

### Is there any code involved? 
 - nope

**Comment by BrunoS3D** [comment] 2021-08-19 01:05
Same problem here :/

**Comment by farfromrefug** [comment] 2021-08-19 06:20
@mukaschultze the issue mostly comes from using the wrong fragment manager. Could you create a simple repro example project?

**Comment by edusperoni** [comment] 2021-08-19 10:15
@farfromrefug the issue is probably present on your demos as well

You might need to target @nativescript/core@next, though, as https://github.com/NativeScript/NativeScript/pull/9517 may be required (it is required for angular at least).

After you change the device theme, when returning to the app, the activity is destroyed and recreated (see the linked PR event list). You might need to save something on `saveActivityState` and restore/wipe these values on `activityCreate`. During this process the native view is completely destroyed (`_tearDownUI` and `onUnloaded` is called), then `onLoaded` is called when coming back.

Also interesting to note that if you suspend the app and resume it again, the views render correctly again

**Comment by farfromrefug** [comment] 2021-08-19 11:57
@edusperoni ok that maybe why i never saw it. In my fork and 8.1.0 the activity is NOT destroyed! 
Dont have much time right now. If someone could test it with 8.1.0 it would help a lot

**Comment by edusperoni** [comment] 2021-08-19 12:27
@farfromrefug in what device did you test? I tested in 8.1 and the activity is being destroyed.

Steps to reproduce:
- launch app
- go to system settings
- toggle dark mode
- switch back to app
- bottom nav tabitemcontent should be bugged
- press home
- switch back to app
- tabitemcontent shows again

This is our activity configuration:

```
<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="AppName"
			android:configChanges="keyboardHidden|layoutDirection|locale|orientation|screenSize"
			android:theme="@style/LaunchScreenTheme"
      android:hardwareAccelerated="true"
      android:launchMode="singleTask"
      android:screenOrientation="nosensor"
      android:stateNotNeeded="true"
      android:windowSoftInputMode="adjustUnspecified">
```

**Comment by farfromrefug** [comment] 2021-08-19 12:50
@edusperoni i just tried the demo vue for material components and there is no crash, no issue. But as said there is also not recreation of the fragments, either with 8.0 or 8.1.0
This is why i asked for a repro example (not angular)

**Comment by farfromrefug** [comment] 2021-08-19 13:05
@edusperoni just update the vue demo app and it does not crash on night mode change. Nor does the activity recreate itself.
You can see the labels color change on the main listview on theme change

**Comment by edusperoni** [comment] 2021-08-19 13:42
@farfromrefug remove `|uiMode` from your android:configChanges. I think we can currently work around it by adding `|uiMode` to the project, but it seems the error is happening whenever there's a config change that's not added to the `android:configChanges`.

Here's a repro with no ui flavors: https://github.com/edusperoni/mdbottomnavbug

**Comment by farfromrefug** [comment] 2021-08-19 13:46
@edusperoni thanks i ll look at it!

**Comment by farfromrefug** [comment] 2021-08-19 16:03
@edusperoni @mukaschultze should be fixed in 5.3.19. Had to rollback on a previous change. Hope it wont have side effects

**Comment by edusperoni** [comment] 2021-08-21 23:21
@farfromrefug actually that rollback "kind of" fixed another issue we were having as well. I'll try to create a demo repo for it.
In sum:
before, when going from one tab to another it could leave a tab in an inconsistent state where frame navigation wouldn't work.
after the change, that doesn't happen, but doing the same steps make the fade transition seems to fade to white instead:

- open app
- navigate to tab 4
- click something and navigate, everything works as expected
- navigate to tab 3
- navigate back to tab 4
- click something to navigate, fade transition fades like the current screen is a white screen instead of the current screen

**Comment by mukaschultze** [comment] 2021-09-02 17:32
@farfromrefug can you please publish a new version that contains the check for undefined `activity.getLifecycle`? The latest `@alpha` works fine but sometimes throws errors on the console

Thanks

**Comment by farfromrefug** [comment] 2021-09-02 19:09
@mukaschultze dont use the alpha.use latest it has the fix

**Comment by Lengo46** [comment] 2022-01-21 08:53
> 

Any instructions how to solve this transitioning. I can't seem to make the white background disappear. I'm breaking my head around this.

**Comment by edusperoni** [comment] 2022-01-21 11:31
Just use a CSS rule:

```
Frame {
   background-color: blue;
}
```

**Comment by farfromrefug** [comment] 2022-01-21 20:11
@edusperoni  can i close this issue? the root issue is fixed right?

**Comment by edusperoni** [comment] 2022-01-21 20:50
I believe so! you can close this

**Closed** 2022-01-21 21:05 UTC
